import type { Media } from './data';

/**
 * Pure helpers — no Node built-ins in here.
 *
 * This file exists separately from lib/shots.ts because that module reads the
 * filesystem at build time, and anything a client component imports gets bundled
 * for the browser. Importing a `node:fs` module from a 'use client' file is a build
 * error, so the shared formatting lives here where both sides can reach it.
 */

export interface ResolvedShot {
  src: string;
  isVideo: boolean;
  /** true when served from public/shots rather than hotlinked */
  local: boolean;
}

/**
 * A caption worth showing. PR bodies are full of autogenerated alt text like
 * "Screenshot (19)" or "Talawa Admin - Google Chrome 05-07-2023 14_30_20";
 * a nearby heading is almost always more useful than either.
 */
export function caption(media: Media): string {
  const junk = (s: string | null): boolean =>
    !s ||
    /Google Chrome/i.test(s) ||
    /^Screenshot[\s(_]/i.test(s) ||
    /^image$/i.test(s.trim());

  const picked = !junk(media.section) ? media.section! : !junk(media.alt) ? media.alt : '';
  return picked.replace(/^\d+\.\s*/, '').trim();
}

export function formatDate(iso: string): string {
  return new Date(`${iso}T00:00:00Z`).toLocaleDateString('en-GB', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    timeZone: 'UTC',
  });
}
